CREATE DATABASE MiniShop;
USE MiniShop;
CREATE TABLE Users(
id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
username VARCHAR(10) NOT NULL,
password VARCHAR(100) NOT NULL,
name VARCHAR(50) NOT NULL,
phone VARCHAR(20) NOT NULL,
address VARCHAR(50) NOT NULL);

CREATE TABLE Products(
id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
name VARCHAR(20) NOT NULL,
category VARCHAR(20) NOT NULL,
price DOUBLE NOT NULL,
description VARCHAR(100) NOT NULL,
fabricationDate DATE NOT NULL,
noItems INT NOT NULL,
photoName VARCHAR(50) NOT NULL
);

CREATE TABLE Orders(
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    userId VARCHAR(36) NOT NULL,
    orderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    totalAmount DOUBLE NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE OrderItems(
    id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
    orderId VARCHAR(36) NOT NULL,
    productId VARCHAR(36) NOT NULL,
    quantity INT NOT NULL,
    unitPrice DOUBLE NOT NULL,
    FOREIGN KEY (orderId) REFERENCES Orders(id),
    FOREIGN KEY (productId) REFERENCES Products(id)
);