CREATE DATABASE MiniShop;
USE MiniShop;
CREATE TABLE Users(
id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
username VARCHAR(10) NOT NULL,
password VARCHAR(100) NOT NULL,
name VARCHAR(50) NOT NULL,
phone VARCHAR(20) NOT NULL,
address VARCHAR(50) NOT NULL);

CREATE TABLE Products(
id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
name VARCHAR(20) NOT NULL,
category VARCHAR(20) NOT NULL,
price DOUBLE NOT NULL,
description VARCHAR(100) NOT NULL,
fabricationDate DATE NOT NULL,
noItems INT NOT NULL,
photoName VARCHAR(50) NOT NULL
);