plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group 'MiniShop'
version '1.0'

repositories {
    mavenCentral()
}

javafx {
    version = "21"
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    implementation project(':MiniShopModel')
    implementation project(':MiniShopServices')
    implementation project(':MiniShopNetworking')
}
